# Experiment - Optimized TicTacToe

In [20]:
import numpy as np

In [2]:
def board_to_array(board_bin):
    board = np.zeros((3,3,1), dtype=np.uint8)

    board[0,0,:] = (board_bin & 0x40) >> 6
    board[0,1] = (board_bin & 0x4000) >> 14
    board[0,2] = (board_bin & 0x4) >> 2
    board[1,0] = (board_bin & 0x20000) >> 17
    board[1,1] = (board_bin & 0x2) >> 1
    board[1,2] = (board_bin & 0x200) >> 9
    board[2,0] = board_bin & 0b1
    board[2,1] = (board_bin & 0x1000) >> 12
    board[2,2] = (board_bin & 0x10) >> 4
    return board

In [3]:
example_binary_board = 0b01010000000101000000010101010100

In [4]:
board_to_array(example_binary_board)[:,:,0]

array([[1, 0, 1],
       [0, 0, 0],
       [0, 0, 1]], dtype=uint8)

In [5]:
(example_binary_board + 0x11111111) & 0x88888888

0

In [12]:
example_winning_board = example_binary_board | 0x20004000

In [14]:
board_to_array(example_winning_board)[:,:,0]

array([[1, 1, 1],
       [0, 0, 0],
       [0, 0, 1]], dtype=uint8)

In [34]:
test = np.array([0,1,1,1,0,0,0,1,1,0,0,1,0])

In [36]:
print(test)
np.where(test == 1)[0]

[0 1 1 1 0 0 0 1 1 0 0 1 0]


array([ 1,  2,  3,  7,  8, 11])

## TicTacToe vs TicTacToeOptimized

In [7]:
import time
import game

In [8]:
def play_game(game_env):
    game_env.reset_game()
    positions = []
    positions_sim = []
    time_sim = []
    time_res_sim = 0
    time_ex = []
    time_get_sim = []
    time_get = []
    time_res = 0
    
    tic = time.time()
    game_env.simulate_move(0)
    toc = time.time()
    time_sim.append(toc-tic)
    
    tic = time.time()
    positions_sim.append(game_env.get_current_position_simulation())
    toc = time.time()
    time_get_sim.append(toc-tic)
    
    tic = time.time()
    game_env.simulate_move(1)
    toc = time.time()
    time_sim.append(toc-tic)
    
    tic = time.time()
    positions_sim.append(game_env.get_current_position_simulation())
    toc = time.time()
    time_get_sim.append(toc-tic)
    
    tic = time.time()
    game_env.simulate_move(2)
    toc = time.time()
    time_sim.append(toc-tic)
    
    tic = time.time()
    positions_sim.append(game_env.get_current_position_simulation())
    toc = time.time()
    time_get_sim.append(toc-tic)
    
    tic = time.time()
    game_env.simulate_move(3)
    toc = time.time()
    time_sim.append(toc-tic)
    
    tic = time.time()
    positions_sim.append(game_env.get_current_position_simulation())
    toc = time.time()
    time_get_sim.append(toc-tic)
    
    tic = time.time()
    game_env.reset_simulation()
    toc = time.time()
    time_res_sim = toc-tic
    
    tic = time.time()
    game_env.execute_move(8)
    toc = time.time()
    time_ex.append(toc-tic)
    
    tic = time.time()
    positions.append(game_env.get_current_position())
    toc = time.time()
    time_get.append(toc-tic)
    
    tic = time.time()    
    game_env.execute_move(1)
    toc = time.time()
    time_ex.append(toc-tic)
    
    tic = time.time()
    positions.append(game_env.get_current_position())
    toc = time.time()
    time_get.append(toc-tic)

    tic = time.time()
    game_env.execute_move(4)
    toc = time.time()
    time_ex.append(toc-tic)

    tic = time.time()    
    positions.append(game_env.get_current_position())
    toc = time.time()
    time_get.append(toc-tic)

    tic = time.time()
    game_env.execute_move(2)
    toc = time.time()
    time_ex.append(toc-tic)

    tic = time.time()
    positions.append(game_env.get_current_position())
    toc = time.time()
    time_get.append(toc-tic)

    tic = time.time()
    game_env.execute_move(5)
    toc = time.time()
    time_ex.append(toc-tic)

    tic = time.time()
    positions.append(game_env.get_current_position())
    toc = time.time()
    time_get.append(toc-tic)

    tic = time.time()
    game_env.reset_game()
    toc = time.time()
    time_res = toc-tic
    
    times = {
        "execute_move": np.mean(time_ex),
        "simulate_move": np.mean(time_sim),
        "get_current_position": np.mean(time_get),
        "get_current_position_simulation": np.mean(time_get_sim),
        "reset_game": time_res,
        "reset_simulation": time_res_sim
    }
    return times, positions, positions_sim

In [9]:
no_opt = game.TicTacToe()
opt = game.TicTacToeOptimized()

times_no_opt, pos_no_opt, pos_sim_no_opt  = play_game(no_opt)
times_opt, pos_opt, pos_sim_opt = play_game(opt)

In [10]:
print("execute_move")
print("not optimized: {}" .format(times_no_opt["execute_move"]))
print("optimized: {}" .format(times_opt["execute_move"]))
print("-> {} " .format(
    times_opt["execute_move"]/times_no_opt["execute_move"]
))

print()

print("simulate_move")
print("not optimized: {}" .format(times_no_opt["simulate_move"]))
print("optimized: {}" .format(times_opt["simulate_move"]))
print("-> {} " .format(
    times_opt["simulate_move"]/times_no_opt["simulate_move"]
))

print()

print("get_current_position")
print("not optimized: {}" .format(times_no_opt["get_current_position"]))
print("optimized: {}" .format(times_opt["get_current_position"]))
print("-> {} " .format(
    times_opt["get_current_position"]/times_no_opt["get_current_position"]
))

print()

print("get_current_position_simulation")
print("not optimized: {}" .format(times_no_opt["get_current_position_simulation"]))
print("optimized: {}" .format(times_opt["get_current_position_simulation"]))
print("-> {} " .format(
    times_opt["get_current_position_simulation"]/times_no_opt["get_current_position_simulation"]
))

print()

print("reset_game")
print("not optimized: {}" .format(times_no_opt["reset_game"]))
print("optimized: {}" .format(times_opt["reset_game"]))
print("-> {} " .format(
    times_opt["reset_game"]/times_no_opt["reset_game"]
))

print()

print("reset_simulation")
print("not optimized: {}" .format(times_no_opt["reset_simulation"]))
print("optimized: {}" .format(times_opt["reset_simulation"]))
print("-> {} " .format(
    times_opt["reset_simulation"]/times_no_opt["reset_simulation"]
))

execute_move
not optimized: 0.000141143798828125
optimized: 8.0108642578125e-06
-> 0.05675675675675676 

simulate_move
not optimized: 0.00027304887771606445
optimized: 1.5020370483398438e-05
-> 0.0550098231827112 

get_current_position
not optimized: 0.00015835762023925782
optimized: 8.406639099121094e-05
-> 0.5308641975308642 

get_current_position_simulation
not optimized: 0.00027000904083251953
optimized: 7.444620132446289e-05
-> 0.2757174392935982 

reset_game
not optimized: 4.506111145019531e-05
optimized: 2.002716064453125e-05
-> 0.4444444444444444 

reset_simulation
not optimized: 4.315376281738281e-05
optimized: 6.198883056640625e-05
-> 1.4364640883977902 


In [11]:
for i in range(len(pos_no_opt)):
    print("no opt")
    print(pos_no_opt[i].state[:,:,0])
    print(pos_no_opt[i].state[:,:,1])
    print(pos_no_opt[i].state[:,:,2])
    print(pos_no_opt[i].legal_actions)
    
    print("opt")
    print(pos_opt[i].state[:,:,0])
    print(pos_opt[i].state[:,:,1]) 
    print(pos_opt[i].state[:,:,2]) 
    print(pos_opt[i].legal_actions)


no opt
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1 0 0 1 0 0 1 1 0]
opt
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1 0 0 1 0 0 1 1 0]
no opt
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 1 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 0 0 1 0 0 1 1 0]
opt
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 1 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 0 0 1 0 0 1 1 0]
no opt
[[0 1 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1 0 0 1 0 0 1 1 0]
opt
[[0 1 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1 0 0 1 0 0 1 1 0]
no opt
[[0 0 0]
 [0 1 0]
 [0 0 1]]
[[0 1 1]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 0 0 1 0 0 1 1 0]
opt
[[0 0 0]
 [0 1 0]
 [0 0 1]]
[[0 1 1]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 0 0 1 0 0 1 1 0]
no opt
[[0 1 1]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 1 1]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1 0 0 1 0 0 1 1 0]
opt
[[0 1 1]
